import { Inter } from 'next/font/google'
import './globals.css'
import Home from './page'
import Navbar from './navbar/page'
import Carousel from './carousel/carousel'
import CarouselComponent from './carousel/carousel'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   <>
      
      <Navbar/>
      <CarouselComponent/>
   </>
  )
}
